RemoteBlobStorageWeb/Controllers/ApiController.cs
using Newtonsoft.Json;
using RBS.Helpers;
using RBS.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RBS.Models;

namespace RBS.Controllers
{
    public class ApiController : Controller
    {
        


        private async Task<bool> checkUploadPermissions(string accesstoken){
            //return true;
            return await NightscoutPermissions.CheckUploadPermissions(accesstoken);
        }


        private ActionResult Error(string msg){
            return Json(
                new
                {
                    Error = true,
                    Message = msg
                },
                JsonRequestBehavior.AllowGet);
        } 
        private ActionResult Success<T>(T result, string command){
            return Json(
                new
                {
                    Error = false,
                    Command = command,
                    Result = result
                },
                JsonRequestBehavior.AllowGet);
        } 
       
        public async Task<ActionResult> CreateRequestAsync(string accesstoken, string contents ){

            //var permissions= await NightscoutPermissions.CheckUploadPermissions(accesstoken);
            //var permissions = await NightscoutPermissions.CheckProcessPermissions(accesstoken);
            if (! await this.checkUploadPermissions(accesstoken))
            {
                return this.Error("CreateRequestAsync Denied");
            }
           


            if(string.IsNullOrWhiteSpace(contents)) {
                return this.Error("CreateRequestAsync Denied: invalid parameter contents");
            }

           

            var g = Guid.NewGuid().ToString();
            var reading = new RBS_Blob
            {
                CreatedOn = DateTime.Now,
                ModifiedOn = DateTime.Now,
                contents = contents,
                uuid = g,
                purpose = "RBS"


            };

            //return this.Error("synthax ok");
            try{
                await MongoConnection.AsyncInsertReading(reading);

            } catch(System.TimeoutException) {
                return Error("Timeout, database down?");
            }

            return Success<RBS_Blob>(reading, "CreateRequestAsync");

            //var content = $"accesstoken: {accesstoken}, b64contents: {b64contents}, guid: {g}";
            //return Content("CreateRequestAsync IS NOT IMPLEMENTED YET:" + content);    
        }




        public async Task<ActionResult> FetchContents(string accesstoken){
            
            if (!await this.checkUploadPermissions(accesstoken))
            {
                return this.Error("FetchContents Denied");
            }
            List<RBS_Blob> readings;
            try
            {
                readings = await MongoConnection.GetPendingReadingsForProcessing();
            }
            catch (Exception ex)
            {
                return Error("FetchContents Failed: " + ex.Message);
            }

            var result = "";
           
            foreach (var item in readings)
            {
                result += $"{item.ModifiedOn}|{item.contents}\r\n";
            }
            return Content(result, "text/plain");
            //var content = $"processing_accesstoken: {processing_accesstoken}";
            //return Content(System.Reflection.MethodBase.GetCurrentMethod().Name + " IS NOT IMPLEMENTED YET:" + content);
        }

       
        public ActionResult Index()
        {
            var content = @"
{ available_methods: ""
/api/CreateRequestAsync -> Object{uuid:String|null, error:false|true, msg:String}
 params:   -contents
  -accesstoken

""} 

";
            return Content(content, "application/json");
            //the minutes parameter is often 1440 (24 hours), telling you how long back you should do the search
            //In nightscout context it is mostly redundant as the maxCount will search as long back as needed.
            //we ignore that parameter
            //Logger.LogInfo("Accesing Glucose Index");


           
        }
    }
}

RemoteBlobStorageWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using RBS.Utils;
using System.IO;
using System.Globalization;
using System.Web.Hosting;
using RBS.Helpers;
using System.Threading.Tasks;

namespace RBS.Controllers
{
    public class HomeController : Controller
    {
      
        public ActionResult Index()
        {
            //database indexes, run it via mongo shell: 
            //db.librereadings.createIndex({ uuid: 1});
            //db.librereadings.createIndex({ status: 1});
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            Logger.LogInfo("Accesing Home");
            return View();
        }

        public ActionResult UploadRawReading() {
            

            return View("UploadRawReading");
        }

        public ActionResult ViewLogs()
        {
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            ViewData["Runtime"] = isMono ? "Mono" : ".NET";
            Logger.LogInfo("Accesing Logs");
            return View("LogsIndex");
        }

        [HttpPost]
        public ActionResult VerifyViewLog(string logsecret)
        {
            if(logsecret != null && logsecret.Length > 11 && Config.DebugViewLogSecret == logsecret) {
                var today = DateTime.Now.ToString("dddd", CultureInfo.InvariantCulture);
                var logfile = Path.Combine(HostingEnvironment.ApplicationPhysicalPath, "Logs",$"libreoop.log");

                try
                {
                    ViewBag.logdata = System.IO.File.ReadAllText(logfile);
                    return View("LogsIndex");
                } catch (Exception ex) {
                    return Content($"Could not read log file due to exception: {ex}");
                }
            }
            return View("Error");
        }


    }
}

RemoteBlobStorageWeb/Views/Home/Index.cshtml
@{
    
    ViewBag.Title = "Home Page";

}

    <div class="container body-content">
        




<div>
    <h1>Welcome to RBS</h1>
        
    <p>Stores arbritary data in a mongo collection </p>


     

    </div>

</div>


        <hr />
        <footer>Copyright bjorninge.no 2018. By submitting readings to this site, you transfer all the legal rights of the contents you submit to the Site owner.
        Any and all data may be shared with vetted developers from the open source community, but the data will never be made available for commercial interests</footer>
    


@section Scripts {
    <script>
       
    </script>
}

RemoteBlobStorageWeb/Views/Home/LogsIndex.cshtml
@{
    
    ViewBag.Title = "Logs";

}

<div>
    <h1>Logs</h1>
    <p>This is a custom server that behaves like a Dexcom Share server, but will fetch its glucose values from nightscout</p>
    <p>To view todays logs, please define an environment variable (app setting in azure) called Log_Secret and use a value of at least 12 characters</p>
    <p>
       You must match that secret in the form below to be able to view logs
    </p>

   @using (Html.BeginForm("VerifyViewLog", "Home", FormMethod.Post))
{
    <input type="password" name="logsecret" />

    <input type="submit" value="Submit to view logs" />
}

</div>

@if (ViewBag.logdata != null) {
 <h2>logdata</h2>
 <pre>@ViewBag.logdata</pre>
}

@section Scripts {
    <script>
      
    </script>
}

RemoteBlobStorageWeb/Views/Home/UploadRawReading.cshtml
@{

    ViewBag.Title = "Logs";

}

<div>
    <h1>Upload raw libre reading</h1>
    <p>
    </p>

    @using (Html.BeginForm("CreateRequestAsync", "Api", FormMethod.Post))
    {
        <table>
            <tr>
                <td><label for="accesstoken">Accesstoken:</label> </td>
                <td><input type="text" id="accesstoken" name="accesstoken" size="40" /></td>
            </tr>
            <tr>
                <td><label for="contents">Contents</label> </td>
                <td><textarea name="contents" id="contents" rows="20" cols="100"></textarea></td>
            </tr>

        </table>


       
        <input type="submit" value="Submit contents" />
    }
</div>




@section Scripts {
    <script>


    </script>
}