RemoteBlobStorageWeb/Controllers/TokenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RBS.Controllers
{
    public class TokenController : Controller
    {
        private bool checkValidUser(string accountName, string password, string applicationId)
        {
            if (accountName.Length == 0 || password.Length == 0 || applicationId.Length == 0)
            {
                Logger.LogInfo($"Invalid request, account or password was invalid");
                return false;
            }

            //future: do additional checks here
            //For now we just allow any combination of username and password
            return true;
        }

        private Guid createGuidAndStoreIt()
        {
            var g = Guid.NewGuid();
            //future: store the guid somewhere
            //For now we don't have any authentication, and accept any guid/sessionid for retrieving glucose
            //so just return it!
            Logger.LogInfo($"Created GUID for user");
            return g;
        }

        public ActionResult Index(string accountName, string password, string applicationId)
        {
            Logger.LogInfo("Accessing Token Index");
            accountName = accountName ?? "";
            password = password ?? "";
            applicationId = applicationId ?? "";

            var account2 = accountName.Length > 0 ? accountName : "Unknown?";
            Logger.LogInfo($"Token request for user {account2}");
            if (this.checkValidUser(accountName, password, applicationId))
            {
                return Json(this.createGuidAndStoreIt(), JsonRequestBehavior.AllowGet);
            }

            return Json(
                new
                {
                    Error = "true",
                    Message = "You should specify an accountname, password and applicationid in a post to this endpoint"
                },
                JsonRequestBehavior.AllowGet);
        }
    }
}

RemoteBlobStorageWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Remote Blob Storage</title>
    <link href="/Content/bootstrap.css" rel="stylesheet"/>
    <link href="/Content/site.css" rel="stylesheet"/>
    <link href="/Content/jquery.powertip.min.css" rel="stylesheet"/>
        
    <script src="/Scripts/modernizr-2.8.3.js"></script>
    <script src="/scripts/prettyprint.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LibreOOPAlgoWeb", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Upload contents", "UploadRawReading", "Home")</li>
                    <!--<li>@Html.ActionLink("Go to CustomShareServer Login", "Index", "Token")</li>
                    <li>@Html.ActionLink("Get glucose", "Index", "Glucose")</li>
                    <li>@Html.ActionLink("View logs", "ViewLogs", "Home")</li> -->
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/jquery.powertip.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>